### ISSUE TITLE
LICENSE / COPYING file?

### ISSUE THREAD

**Issue by cwebber** [sjl/cl-chip8#2]
Heya!  Thanks for working on this project; it's nice to have a libre implementation of the PICO-8, which seems like a pretty cool system.  And I enjoyed your blogposts!

However!  You're missing a COPYING / LICENSE file... without it, your code isn't really licensed under the license you're claiming correctly.  (It would also be great if you could add a copyright header to each file with the appropriate licensing information too, but the COPYING / LICENSE file with the appropriate legal text is more important!)

**Comment by sjl** [comment]
This has nothing to do with the PICO-8 (aside from the CHIP-8 also having the number "8" in its name), but okay...

I'll add the single file, but license headers at the top of every file are awful and unnecessary noise.
